[package]
name = "CodeQuill"
version = "0.1.0"
edition = "2024"

[dependencies]

actix-web = '4'
actix-web-actors = '4'
serde = { version = '1.0', features = ['derive'] }
serde_json = '1.0'
tokio = { version = '1', features = ['full'] }
uuid = { version = '1', features = ['v4', 'serde'] }
futures = '0.3'
