[package]
name = "CodeQuill"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-web-actors = "4"
actix = "0.13"
uuid = { version = "1.3.0", features = ["v4"] }
log = "0.4"
env_logger = "0.10"